language: php
php:
  - '7.2'
  - '7.3'
  - '7.4'

install:
  - make -C src deps

script:
  - php tests/run.php

notifications:
  irc:
    channels:
      - "chat.freenode.net#garradin"
    template:
      - "%{build_number} by %{author} on %{branch}: %{message} "
      - "Build details: %{build_url}"
    use_notice: false
    skip_join: true